### ISSUE TITLE
2-pass mode randomly stops/freezes

### ISSUE THREAD

**Issue by malnvenshorn** [baxtree/subaligner#38]
###Describe the bug
The 2-pass mode stops/freezes  at some random point. The last run stopped around minute 40. I also had runs were at stopped around minute 10 or after minute 80.

###To Reproduce
I'm just running `subaligner_2pass -v video.mp4 -s ger.srt -so`.

###Expected behavior
That the process finishes with the resulting subtitle.

###Screenshots and logs
[output.log](https://github.com/baxtree/subaligner/files/5075087/output.log)

###Desktop (please complete the following information):
 - Operating System: Linux 5.7.12-arch1-1 x86_64 GNU/Linux
 - Python Version: 3.8.5

**Comment by baxtree** [comment]
Hi, @malnvenshorn, Thanks for trying subaligner.

Your log shows the aligning was stuck on extracting the audio segment between `00:39:51.080` to `00:39:55.000`. Looks like the earlier segments were successfully extracted and loaded.

I am wondering how many cores your machine has. By default, subaligner will utilise half of the logic cores but they could be way more than the processes ffmpeg can handle. Can you try to lower the number of workers by setting the `MAX_WORKERS` environment variable? For example, prepend `MAX_WORKERS=2` to that command and ran it again to see if the freezing re-appear or not.

**Comment by malnvenshorn** [comment]
I tried limiting the number of workers as suggested. It works only with `MAX_WORKERS=1`

**Comment by baxtree** [comment]
Nice try, @malnvenshorn. The fix on the concurrency issue was merged into master. Please reinstall subaligner from source and try your job again.

**Comment by malnvenshorn** [comment]
Hi, checked out the latest version, but the issue still persists for me. It only works with on thread. 

[output.log](https://github.com/baxtree/subaligner/files/5112284/output.log)

**Comment by baxtree** [comment]
Hi, @malnvenshorn. Some dependencies installed are definitely not thread-safe. Just merged some improvement into master and please try it again. Sorry but I could not replicate the error you got on my machine and my plan is to spin up a virtual machine identical to yours if the above fix doesn't work. So may need more information about your environment and thank you in advance.

PS: I also fixed the configuration on logging and you can still get detailed logs by passing in `--debug` to your command.

**Comment by malnvenshorn** [comment]
Still having the same issue:  [output.log](https://github.com/baxtree/subaligner/files/5112503/output.log)

I'm using 64 Bit Arch Linux with kernel 5.8.1-arch1-1 and python version 3.8.5.

Installed  python packages: [pip.txt](https://github.com/baxtree/subaligner/files/5112517/pip.txt)

If you need more information feel free to ask.

**Comment by baxtree** [comment]
Hi, @malnvenshorn, I cannot find the latest Docker image for kernel 5.8.1-arch1-1 and I ran your command with kernel 4.19.76-linuxkit x86_64 GNU/Linux and python 3.8.5. Three cores were used and the video duration was 02:19:35. It did not freeze and here is the log: [output.log](https://github.com/baxtree/subaligner/files/5117348/output.log)

Would you mind trying the following steps and see if you can replicate what you got on 5.8.1-arch1-1?
```
docker pull archlinux
docker run -v `pwd`:`pwd` -w `pwd` -it archlinux
pacman -Syu gcc python python-pip ffmpeg espeak
pip install numpy
pip install -r requirements.txt
pip install -e . --ignore-installed
bin/subaligner_2pass -v video.mp4 -s ger.srt -so -d
```

**Comment by baxtree** [comment]
Got further update following my last message on this. I managed to install Linux 5.7.6-arch1-1 x86_64 GNU/Linux on my machine but still cannot replicate the freeze. `MAX_WORKERS` was set to 4 and the video duration was 02:19:35. Tries it with `-so` being present and being absent. Can I ask how much memory did you allocate to subaligner? @malnvenshorn 
<img width="411" alt="osinfo" src="https://user-images.githubusercontent.com/351072/91640513-060e4500-ea16-11ea-9fac-28f777f68166.png">

**Comment by baxtree** [comment]
Hi, @malnvenshorn, following up on this, if your video and subtitle files do not contain private or sensitive data, do you mind sharing them? So I can download and have a closer look.

**Comment by baxtree** [comment]
Closing this issue due to the lack of activities. Can be reopened if the freezing can be reproducible on ArchLinux.
